MODEL:
  ARCHITECTURE: "DTF"
  DTF:
    VIDEO_MODE: 'c3d'
    NUM_CLIPS: 64
    JOINT_SPACE_SIZE: 256
    FEATPOOL:
      INPUT_SIZE: 500
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 4
    FEAT2D:
      NAME: "pool_b"
      POOLING_COUNTS: [15,8,8]
    TEXT_ENCODER:
      NAME: "BERT"
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 9
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.3
      CONTRASTIVE_WEIGHT: 0.1
OUTPUT_DIR: "./activity/dist/full_model"
DATASETS:
  NAME: "activitynet"
  TRAIN: ("activitynet_train", )
  TEST: ("activitynet_test",)
INPUT:
  NUM_PRE_CLIPS: 256
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.0008
  BATCH_SIZE: 12
  MILESTONES: (7, 15)
  MAX_EPOCH: 15
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 16
  FREEZE_BERT: 4
  ONLY_IOU: 6
  SKIP_TEST: 1
  USE_STATIC: True
  USE_GNN: True
  GNN_SPARSE: True
  GNN_MODE: 'gauss'   # 'gauss' or 'd' or 'gat' or 'mlp'
  GNN_LAYERS: 2
  GNN_U: 5.0
  GNN_STEP: 0.1
  POS_EMBED: 'sine'   # choices=['trainable', 'sine', 'learned']
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 12
  CONTRASTIVE_SCORE_POW: 0.5
